### ISSUE TITLE
README의 설치 방법으로 시도하였으나 설치가 되지 않습니다. 패키지 이름이 다른 것 같네요.

### ISSUE THREAD

**Issue by pin0156** [yomybaby/atom-korean-spell-daum#1]
설치 방법 수정 요청드립니다.

이전:
apm install korean-spell-daum

이후:
1. install atom
- 1.1. download atom:https://atom.io/
- install atom-korean-spell-daum
- 2.1. git clone https://github.com/yomybaby/atom-korean-spell-daum.git
- 2.2. cd atom-korean-spell-daum
- 2.3. apm install
- 2.4. apm link .
- 2.5. apm install korean-spellchekcer-daum

**Comment by yomybaby** [comment]
이 저장소의 GitHub 알람이 꺼져있었네요.(왜 꺼져있었는지는 모르겠어요.)
그래서 어제야 이사항을 파악했습니다.

해당 문서 수정했습니다.  아래와 같이 설치해보세요.

```
apm install korean-spellchecker-daum
```

이슈 발급해주셔서 감사합니다.
