### ISSUE TITLE
검사기 창의 height가 매우 좁게 열립니다.

### ISSUE THREAD

**Issue by YongHee-Kim** [yomybaby/atom-korean-spell-daum#2]
사용환경은 윈도우입니다.

![bugreport](https://cloud.githubusercontent.com/assets/7087745/23787907/984f47f8-05b7-11e7-9691-cd9351fd3451.gif)

**Comment by yomybaby** [comment]
알려주셔서 감사합니다.
어제 이 이슈 수정했는데 따로 버그리포팅해주신줄도 몰랐네요.^^
적용 버튼도 크게 만들었어요.

**Comment by yomybaby** [comment]
8f23a47fe95e42d66753ddeff3d783b2567497e5
